#!/usr/bin/env python3
"""Plot total cooling rates vs. temperature for the nearest n_H in a grid."""

from __future__ import annotations

import argparse
import csv
import math
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass
class CoolingTotalsRow:
    temperature: float
    hydrogen_density: float
    line_rate: float
    free_free_rate: float
    compton_rate: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Plot the line, free-free, and Compton cooling rates as a function of "
            "temperature for the closest hydrogen density present in the "
            "cooling_component_totals.csv file generated by "
            "scripts/extract_top_cooling_components.py."
        )
    )
    parser.add_argument(
        "totals_csv",
        type=Path,
        help="Path to cooling_component_totals.csv.",
    )
    parser.add_argument(
        "target_density",
        type=float,
        help="Desired hydrogen density n_H (cm^-3). The nearest grid value is used.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("cooling_rate_vs_temperature.png"),
        help=(
            "Output image file (default: ./cooling_rate_vs_temperature.png). "
            "Use '-' to skip saving."
        ),
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot interactively in addition to saving it.",
    )
    parser.add_argument(
        "--log-temperature",
        action="store_true",
        default=True,
        help="Use a logarithmic x-axis for temperature.",
    )
    return parser.parse_args()


def load_totals(path: Path) -> List[CoolingTotalsRow]:
    required_columns = {
        "temperature_K",
        "hydrogen_density",
        "total_line_cooling_rate",
        "total_free_free_cooling_rate",
        "total_compton_cooling_rate",
    }
    rows: List[CoolingTotalsRow] = []

    with path.open("r", newline="", encoding="ascii") as handle:
        reader = csv.DictReader(handle)
        missing = required_columns - set(reader.fieldnames or [])
        if missing:
            missing_list = ", ".join(sorted(missing))
            raise ValueError(
                f"Missing required columns in {path}: {missing_list}. "
                "Please regenerate the file with scripts/extract_top_cooling_components.py "
                "so the total cooling rates are available."
            )
        for line_number, raw in enumerate(reader, start=2):
            try:
                rows.append(
                    CoolingTotalsRow(
                        temperature=float(raw["temperature_K"]),
                        hydrogen_density=float(raw["hydrogen_density"]),
                        line_rate=float(raw["total_line_cooling_rate"]),
                        free_free_rate=float(raw["total_free_free_cooling_rate"]),
                        compton_rate=float(raw["total_compton_cooling_rate"]),
                    )
                )
            except (TypeError, ValueError) as exc:
                raise ValueError(
                    f"Could not parse row {line_number} in {path}: {raw}"
                ) from exc

    if not rows:
        raise ValueError(f"No data rows found in {path}")
    return rows


def nearest_density(rows: List[CoolingTotalsRow], target_density: float) -> float:
    densities = sorted({row.hydrogen_density for row in rows})
    if not densities:
        raise ValueError("No hydrogen density values available in the totals file.")

    def metric(value: float) -> float:
        if value > 0.0 and target_density > 0.0:
            return abs(math.log10(value) - math.log10(target_density))
        return abs(value - target_density)

    return min(densities, key=metric)


def select_rows_at_density(
    rows: List[CoolingTotalsRow],
    density: float,
    *,
    rel_tol: float = 1e-6,
    abs_tol: float = 1e-12,
) -> List[CoolingTotalsRow]:
    selected = [
        row
        for row in rows
        if math.isclose(row.hydrogen_density, density, rel_tol=rel_tol, abs_tol=abs_tol)
    ]
    if not selected:
        raise ValueError(
            f"No rows matched hydrogen_density={density} within tolerance "
            f"(rel_tol={rel_tol}, abs_tol={abs_tol})."
        )
    return sorted(selected, key=lambda row: row.temperature)


def plot_cooling_rates(
    rows: List[CoolingTotalsRow],
    *,
    requested_density: float,
    chosen_density: float,
    output: Path | None,
    show_plot: bool,
    log_temperature: bool,
    plt_module,
) -> None:
    if output is None and not show_plot:
        return
    plt = plt_module
    temperatures = [row.temperature for row in rows]
    line_rates = [abs(row.line_rate) for row in rows]
    free_free_rates = [abs(row.free_free_rate) for row in rows]
    compton_rates = [abs(row.compton_rate) for row in rows]

    all_rates = [value for series in (line_rates, free_free_rates, compton_rates) for value in series]
    positive_values = [value for value in all_rates if value > 0.0]
    floor = min(positive_values) * 0.1 if positive_values else 1e-40
    adjusted_series = [
        [max(value, floor) for value in line_rates],
        [max(value, floor) for value in free_free_rates],
        [max(value, floor) for value in compton_rates],
    ]

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(temperatures, adjusted_series[0], label="Line", color="#1f77b4")
    ax.plot(temperatures, adjusted_series[1], label="Free-Free", color="#ff7f0e")
    ax.plot(temperatures, adjusted_series[2], label="Compton", color="#2ca02c")

    ax.set_xlabel("Temperature (K)")
    ax.set_ylabel("Cooling Rate (erg cm$^{-3}$ s$^{-1}$)")
    if positive_values:
        max_value = max(positive_values)
        ax.set_yscale("log")
        ax.set_ylim(floor, max_value * 2.0)
    if log_temperature:
        ax.set_xscale("log")
    ax.legend()
    ax.grid(True, which="both", linestyle="--", linewidth=0.5, alpha=0.5)

    density_note = (
        f"n_H target={requested_density:.3g}, nearest grid={chosen_density:.3g} cm^-3"
    )
    ax.set_title(f"Cooling Rates vs Temperature\n{density_note}")
    fig.tight_layout()

    if output is not None:
        fig.savefig(output, dpi=300)
        print(f"Saved plot to {output}")
    if show_plot:
        plt.show()
    else:
        plt.close(fig)


def configure_matplotlib(show_plot: bool):
    import matplotlib

    if not show_plot:
        matplotlib.use("Agg", force=True)
    import matplotlib.pyplot as plt

    return plt


def main() -> None:
    args = parse_args()
    totals_rows = load_totals(args.totals_csv)
    chosen_density = nearest_density(totals_rows, args.target_density)
    selected_rows = select_rows_at_density(totals_rows, chosen_density)

    output_path: Path | None
    if args.output == Path("-"):
        output_path = None
    else:
        output_path = args.output
        if output_path is not None:
            output_path.parent.mkdir(parents=True, exist_ok=True)

    print(
        f"Requested n_H={args.target_density:g} cm^-3; "
        f"using nearest grid value n_H={chosen_density:g} cm^-3 "
        f"({len(selected_rows)} temperature samples)."
    )

    if output_path is None and not args.show:
        print("No figure requested (no output path and --show disabled); skipping plot.")
        return

    plt_module = configure_matplotlib(args.show)
    plot_cooling_rates(
        selected_rows,
        requested_density=args.target_density,
        chosen_density=chosen_density,
        output=output_path,
        show_plot=args.show,
        log_temperature=args.log_temperature,
        plt_module=plt_module,
    )


if __name__ == "__main__":
    main()
